[build]
  command = "npm run build"
  publish = "out"

# 处理Next.js API路由
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY = "true"

# 函数配置
[functions]
  directory = "functions/" 