[build]
  command = "npm run build"
  publish = "out"

# 处理tournament API
[[redirects]]
  from = "/api/tournament"
  to = "/.netlify/functions/tournament"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY = "true"

# 函数配置
[functions]
  directory = "netlify/functions/" 